#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, and on the 9th iteration "Hi" is displayed on a new line
number=0; while [ $number -lt 10 ]; do echo "Best School"; if [ $number -eq 8 ]; then echo "Hi"; fi; number=$(( number+1 )); done
