#!/usr/bin/env bash
# This script is displaying numbers from 1-20, and after 4, 9 and 17 display bad luck
number=0; while [ $number -lt 20 ]; do echo $(( number + 1 )); case $number in 3) echo "bad luck from China";; 8) echo "bad luck from Japan";; 16) echo "bad luck from Italy";;esac; number=$(( number + 1 )); done
